### ISSUE TITLE
Unable to find any services tagged with "tmdb_symfony.psr17.event_dispatchers"

### ISSUE THREAD

**Issue by Machou** [php-tmdb/symfony#36]
Hello

I have this error :

Unable to find any services tagged with "tmdb_symfony.psr17.event_dispatchers", please set it in the configuration explicitly under "tmdb_symfony.options.event_dispatcher.adapter".

I don't know how to fix it ?

I'm on Symfony 5.2

Thanks

**Comment by wtfzdotnet** [comment]
What does your configuration look like?

**Comment by Machou** [comment]
I have create a file ```/config/config.yaml``` :

```yaml
tmdb_symfony:
    api_key: xxx
    options:
        http:
            client: Symfony\Component\HttpClient\Psr18Client
            request_factory: Nyholm\Psr7\Factory\Psr17Factory
            response_factory: Nyholm\Psr7\Factory\Psr17Factory
            stream_factory: Nyholm\Psr7\Factory\Psr17Factory
            uri_factory: Nyholm\Psr7\Factory\Psr17Factory
```

add in ```services.yaml``` :

```yaml
services:
    Symfony\Component\HttpClient\Psr18Client:
        class: Symfony\Component\HttpClient\Psr18Client

    Nyholm\Psr7\Factory\Psr17Factory:
        class: Nyholm\Psr7\Factory\Psr17Factory
```

i have installed :

For PSR-7: HTTP Message Interface, for example nyholm/psr7
For PSR-14: Event Dispatcher, for example symfony/event-dispatcher
For PSR-17: HTTP Factories, for example nyholm/psr7
For PSR-18: HTTP Client, for example guzzlehttp/guzzle

composer require php-http/cache-plugin:^1.7
compose require monolog/monolog

and latest :

composer require php-tmdb/api:^4

**Comment by ivan1986** [comment]
```yaml
tmdb_symfony:
  api_key: '%env(TMDB_API_KEY)%'
  options:
    event_dispatcher:
      adapter: Symfony\Component\EventDispatcher\EventDispatcher
    http:
      client: Symfony\Component\HttpClient\Psr18Client
      request_factory: Nyholm\Psr7\Factory\Psr17Factory
      response_factory: Nyholm\Psr7\Factory\Psr17Factory
      stream_factory: Nyholm\Psr7\Factory\Psr17Factory
      uri_factory: Nyholm\Psr7\Factory\Psr17Factory

services:
  Symfony\Component\HttpClient\Psr18Client:
    class: Symfony\Component\HttpClient\Psr18Client

  Nyholm\Psr7\Factory\Psr17Factory:
    class: Nyholm\Psr7\Factory\Psr17Factory

  Symfony\Component\EventDispatcher\EventDispatcher:
    tags:
      - { name: tmdb_symfony.psr17.event_dispatchers }
```

works
