### ISSUE TITLE
non-existent service "tmdb.cache_handler"

### ISSUE THREAD

**Issue by lookbadgers** [php-tmdb/symfony#8]
Just upgrading from "wtfzdotnet/php-tmdb-api": ">=1.2.0" to the latest version "php-tmdb/symfony": "~2.0" and have an issue.

The service "tmdb.client" has a dependency on a non-existent service "tmdb.cache_handler".

If I comment out /php-tmdb/symfony/Resources/config/services.xml [32-34] it works

```
<!--            <call method="setCacheHandler">
                <argument type="service" id="tmdb.cache_handler" />
            </call>-->
```

This is my configuration:

```
tmdb_symfony:
    api_key: x
    options:
        cache:
            enabled: true
            path: "/tmp/php-tmdb-api"

        log:
            enabled: true
            path: "/tmp/php-tmdb-api.log"  
```

Great package by the way, thank you.

**Comment by wtfzdotnet** [comment]
Sorry for getting back this late I've been clogged up for a while, I think this has to do with the fact you missed an part of the documentation:

You are required to define a doctrine cache handler yourself that you will use for response caching:

```
doctrine_cache:
    providers:
        tmdb_cache:
            file_system:
                directory: %kernel.root_dir%/cache/tmdb
```

The cache provider `tmdb_cache` is configured as following:

```
tmdb_symfony:
    options:
        cache:
            enabled: true
            handler: tmdb_cache
```

I agree the code or documentation will need improvement, I will try to tackle this somewhere in the near future.
